name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake
          # Жестко связываем пути zlib, чтобы обойти ошибку проверки заголовков
          sudo mkdir -p /usr/include
          sudo ln -sf /usr/include/x86_64-linux-gnu/zlib.h /usr/include/zlib.h || true

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" virtualenv buildozer

      - name: Fix Permissions and Compile APK
        run: |
          # Исправляем права владельца папки для Android NDK
          sudo chown -R runner:docker .
          export BUILDOZER_ALLOW_KIVY_ROOT=1
          # Запускаем сборку с автоматическим тихим принятием всех лицензий Google
          buildozer android debug --accept-sdk-license

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: II_Promty_Application
          path: bin/*.apk
